---

- name: Query the RHACM OAS InfraEnv for the Discovery ISO
  kubernetes.core.k8s_info:
    api_version: agent-install.openshift.io/v1beta1
    kind: InfraEnv
    namespace: "{{ infraenv.namespace }}"
    name: "{{ infraenv.name }}"
  register: infraenv_info
  retries: 30
  delay: 10
  until: infraenv_info.resources[0].status.isoDownloadURL != ""
  ignore_errors: true

- name: Download Discovery ISO
  get_url:
    url: "{{ infraenv_info.resources[0].status.isoDownloadURL }}"
    dest: "/tmp/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    validate_certs: false

- name: Delete the previous iso if present
  community.vmware.vsphere_file:
    host: '{{ vsphere_secret.resources[0].data.vcenter_fqdn | b64decode }}'
    username: '{{ vsphere_secret.resources[0].data.vcenter_username | b64decode }}'
    password: '{{ vsphere_secret.resources[0].data.vcenter_password | b64decode }}'
    validate_certs: "{{ (vsphere_secret.resources[0].data.skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
    datacenter: "{{ cluster_configmap_info.resources[0].data.vsphere_datacenter }}"
    datastore: "{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}"
    path: "{{ cluster_configmap_info.resources[0].data.vsphere_iso_folder | default('ISOs') }}/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    state: absent
  ignore_errors: true

- name: Upload Discovery ISO to the target Cluster Host
  community.vmware.vsphere_copy:
    hostname: '{{ vsphere_secret.resources[0].data.vcenter_fqdn | b64decode }}'
    username: '{{ vsphere_secret.resources[0].data.vcenter_username | b64decode }}'
    password: '{{ vsphere_secret.resources[0].data.vcenter_password | b64decode }}'
    validate_certs: "{{ (vsphere_secret.resources[0].data.skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
    src: "/tmp/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    datacenter: "{{ cluster_configmap_info.resources[0].data.vsphere_datacenter }}"
    datastore: "{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}"
    path: "{{ cluster_configmap_info.resources[0].data.vsphere_iso_folder | default('ISOs') }}/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    timeout: "600"
  retries: 10
  delay: 10
  until: upload_iso.changed|bool
  ignore_errors: true
  register: upload_iso

- name: Delete local Discovery ISO
  file:
    path: "/tmp/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    state: absent
